\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[left=1.1in, right=1.1in, top=1.1in, bottom=1.1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={Stat 435 Lecture Notes 3},
            pdfauthor={Xiongzhi Chen; Washington State University},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{{#1}}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{{#1}}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\ImportTok}[1]{{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{{#1}}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{{#1}}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{{#1}}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{{#1}}}}
\newcommand{\BuiltInTok}[1]{{#1}}
\newcommand{\ExtensionTok}[1]{{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{{#1}}}
\newcommand{\RegionMarkerTok}[1]{{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{{#1}}}}
\newcommand{\NormalTok}[1]{{#1}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{Stat 435 Lecture Notes 3}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{Xiongzhi Chen \\ Washington State University}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
    \date{}
    \predate{}\postdate{}
  
\usepackage{bbm}
\usepackage{amssymb}
\usepackage{amsmath}
\usepackage{graphicx,float}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\section{}\label{section}

\section{Linear regression with a qualitative
predictor}\label{linear-regression-with-a-qualitative-predictor}

\subsection{Motivation}\label{motivation}

\begin{itemize}
\item
  How is \texttt{Balance} of a credit card related to a user's
  \texttt{Gender}?
\item
  How is \texttt{Balance} of a credit card related to a user's
  \texttt{Ethnicity}?
\end{itemize}

\subsection{Motivation}\label{motivation-1}

\begin{center}\includegraphics[width=0.7\linewidth]{Stat435LectureNotes3_notes_files/figure-latex/addata2-1} \end{center}

\subsection{Model 1: 2 levels}\label{model-1-2-levels}

\begin{itemize}
\tightlist
\item
  Coding: \texttt{Gender} has 2 levels, \texttt{Male} and
  \texttt{Female}
\item
  \emph{dummy variable}: \(x_i =0\) if \(i\)th person is \texttt{Female}
  and \(x_i =1\) if \(i\)th person is \texttt{Male}
\item
  Model: \(y_i = \beta_0 + \beta_1 x_i + \varepsilon_i\), which induces
  2 submodels:
\item
  \(y_i = \beta_0 + \beta_1 + \varepsilon_i\) if \(i\)th person is
  \texttt{Male}
\item
  \(y_i = \beta_0 + \varepsilon_i\) if \(i\)th person is \texttt{Female}
\end{itemize}

\emph{Note:} dummy variable follows coding by R, for which the first
level \texttt{Female} is the baseline

\subsection{Model 1: 2 levels}\label{model-1-2-levels-1}

Model: \(y_i = \beta_0 + \beta_1 x_i + \varepsilon_i\)

\begin{itemize}
\tightlist
\item
  \(x_i =0\) if \(i\)th person is \texttt{Female}, and \(x_i =1\) if
  \(i\)th person is \texttt{Male}
\item
  \(\beta_0\): average \texttt{Balance} for females
\item
  \(\beta_1\): average difference in balance between \emph{males and
  females}
\end{itemize}

\emph{Remark:} coding of a dummy variable is arbitrary and should be
easily interpretable

\subsection{Fitting the Model 1}\label{fitting-the-model-1}

\begin{verbatim}

Call:
lm(formula = Balance ~ Gender, data = creditData)

Coefficients:
(Intercept)   GenderMale  
     529.54       -19.73  
\end{verbatim}

\begin{itemize}
\tightlist
\item
  \texttt{Female}s have an average \texttt{balance} of \$529.54;
  \texttt{Female} baseline
\item
  \texttt{Male}s have an average \texttt{balance} of \$(529.54-19.73)=
  \$509.80
\end{itemize}

\emph{Note:} in R, by default the first level \texttt{Female} is the
baseline

\subsection{Testing the Model 1}\label{testing-the-model-1}

\begin{verbatim}

Call:
lm(formula = Balance ~ Gender, data = creditData)

Residuals:
    Min      1Q  Median      3Q     Max 
-529.54 -455.35  -60.17  334.71 1489.20 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)   529.54      31.99  16.554   <2e-16 ***
GenderMale    -19.73      46.05  -0.429    0.669    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 460.2 on 398 degrees of freedom
Multiple R-squared:  0.0004611, Adjusted R-squared:  -0.00205 
F-statistic: 0.1836 on 1 and 398 DF,  p-value: 0.6685
\end{verbatim}

\begin{itemize}
\tightlist
\item
  If model assumptions are met, \texttt{Gender} is not significant on
  affecting average \texttt{balance} at type I error level 0.05 based on
  F-statistic (or the p-value of \texttt{GenderMale})
\end{itemize}

\subsection{Model 2: 3 levels}\label{model-2-3-levels}

\texttt{Ethnicity} has 3 levels \texttt{African\ American} (1st level
and baseline in R), \texttt{Asian}, and \texttt{Caucasian}. \emph{2
dummy variables} are needed:

\begin{itemize}
\tightlist
\item
  \(x_{i1} =0\) if \(i\)th person is \emph{not} \texttt{Asian}, and
  \(x_{i1} =1\) if \(i\)th person is \texttt{Asian}
\item
  \(x_{i2} =0\) if \(i\)th person is \emph{not} \texttt{Caucasian}, and
  \(x_{i2} =1\) if \(i\)th person is \texttt{Caucasian}
\item
  Model:
  \[y_i = \beta_0 + \beta_1 x_{i1} +\beta_2 x_{i2} + \varepsilon_i\]
\end{itemize}

\subsection{Model 2: 3 levels}\label{model-2-3-levels-1}

Model:
\[y_i = \beta_0 + \beta_1 x_{i1} +\beta_2 x_{i2} + \varepsilon_i\]

\begin{itemize}
\tightlist
\item
  Codings on previous slide
\item
  \(\beta_0\): average \texttt{balance} for \texttt{African\ American}
\item
  \(\beta_1\): average difference in \texttt{balance} between
  \texttt{Asian} and \texttt{African\ American}
\item
  \(\beta_2\): average difference in \texttt{balance} between
  \texttt{Caucasian} and \texttt{African\ American}
\end{itemize}

\subsection{Fitting the Model 2}\label{fitting-the-model-2}

\begin{verbatim}

Call:
lm(formula = Balance ~ Ethnicity, data = creditData)

Coefficients:
       (Intercept)      EthnicityAsian  EthnicityCaucasian  
            531.00              -18.69              -12.50  
\end{verbatim}

\begin{itemize}
\tightlist
\item
  \texttt{African\ American}s have an average \texttt{balance} of \$531
\item
  \texttt{Asian}s have an average \texttt{balance} of \$(531-18.69)=
  \$512.31
\item
  \texttt{Caucasian}s have an average \texttt{balance} of \$(531-12.50)=
  \$518.5
\end{itemize}

\subsection{Testing the Model 2}\label{testing-the-model-2}

\begin{verbatim}

Call:
lm(formula = Balance ~ Ethnicity, data = creditData)

Residuals:
    Min      1Q  Median      3Q     Max 
-531.00 -457.08  -63.25  339.25 1480.50 

Coefficients:
                   Estimate Std. Error t value Pr(>|t|)    
(Intercept)          531.00      46.32  11.464   <2e-16 ***
EthnicityAsian       -18.69      65.02  -0.287    0.774    
EthnicityCaucasian   -12.50      56.68  -0.221    0.826    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 460.9 on 397 degrees of freedom
Multiple R-squared:  0.0002188, Adjusted R-squared:  -0.004818 
F-statistic: 0.04344 on 2 and 397 DF,  p-value: 0.9575
\end{verbatim}

If model assumptions are met, at type I error level 0.05,
\texttt{Ethnicity} does not significantly affect average
\texttt{balance} based on the F-statistic

\subsection{Testing the Model 2}\label{testing-the-model-2-1}

\begin{verbatim}
# A tibble: 3 x 5
  term               estimate std.error statistic  p.value
  <chr>                 <dbl>     <dbl>     <dbl>    <dbl>
1 (Intercept)           531.       46.3    11.5   1.77e-26
2 EthnicityAsian        -18.7      65.0    -0.287 7.74e- 1
3 EthnicityCaucasian    -12.5      56.7    -0.221 8.26e- 1
\end{verbatim}

If model assumptions are met and \texttt{Ethnicity} does not
significantly affect average \texttt{balance}, there is no need to check

\begin{itemize}
\tightlist
\item
  whether there is significant difference in average \texttt{balance}
  between \texttt{Asian}s and \texttt{African\ American}s or between
  \texttt{Caucasian}s and \texttt{African\ American}s
\end{itemize}

\subsection{Diagnostics}\label{diagnostics}

Diagnostics are the same as those for simple linear regression with a
quantitative predictor.

\begin{center}\includegraphics{Stat435LectureNotes3_notes_files/figure-latex/unnamed-chunk-6-1} \end{center}

\section{Multiple linear regression}\label{multiple-linear-regression}

\subsection{Motivation}\label{motivation-2}

\begin{itemize}
\item
  How is \texttt{sales} (in thousands of units) for a particular product
  related to advertising budgets (in thousands of dollars) for
  \texttt{TV}, \texttt{radio} \emph{and} \texttt{newspaper}?
\item
  Model: \texttt{sales} = \(\beta_0\) + \(\beta_1 \times\) \texttt{TV} +
  \(\beta_2\times\) \texttt{radio} + \(\beta_3 \times\)
  \texttt{newspaper} + \(\varepsilon\)
\end{itemize}

We want to examine the relationship between \texttt{sales} and budgets
for \texttt{TV}, \texttt{radio} and \texttt{newspaper} \emph{jointly},
instead of \emph{marginally}.

\subsection{Model}\label{model}

Response \(Y\) and \(p\) predictors \(X_1, X_2, \ldots, X_p\), bound by
model

\[Y = \beta_0 + \beta_1 X_1 +\beta_2 X_2 + \cdots + \beta_p X_p + \varepsilon\]

\begin{itemize}
\item
  \(\beta_j\): change in units in \(E(Y)\) for a unit change in \(X_j\)
  while holding all other predictors fixed
\item
  \(\varepsilon\): random error term with \(E(\varepsilon)=0\) and
  \(Var(\varepsilon)=\sigma^2\)
\item
  Estimate coefficient vector
  \(\boldsymbol{\beta}=(\beta_0,\beta_1,\ldots,\beta_p)\) by the
  \emph{least squares method}; estimate
  \(\hat{\boldsymbol{\beta}}=(\hat{\beta}_0,\hat{\beta}_1,\ldots,\hat{\beta}_p)\)
  as \emph{LSE (least squares estimate)}
\end{itemize}

\subsection{Fitting model}\label{fitting-model}

Joint model vs marginal model:

\begin{verbatim}
# A tibble: 4 x 5
  term        estimate std.error statistic  p.value
  <chr>          <dbl>     <dbl>     <dbl>    <dbl>
1 (Intercept)  2.94      0.312       9.42  1.27e-17
2 TV           0.0458    0.00139    32.8   1.51e-81
3 radio        0.189     0.00861    21.9   1.51e-54
4 newspaper   -0.00104   0.00587    -0.177 8.60e- 1
\end{verbatim}

\begin{verbatim}
# A tibble: 2 x 5
  term        estimate std.error statistic  p.value
  <chr>          <dbl>     <dbl>     <dbl>    <dbl>
1 (Intercept)  12.4       0.621      19.9  4.71e-49
2 newspaper     0.0547    0.0166      3.30 1.15e- 3
\end{verbatim}

\begin{verbatim}
# A tibble: 2 x 5
  term        estimate std.error statistic  p.value
  <chr>          <dbl>     <dbl>     <dbl>    <dbl>
1 (Intercept)   7.03     0.458        15.4 1.41e-35
2 TV            0.0475   0.00269      17.7 1.47e-42
\end{verbatim}

\subsection{Testing on all
coefficients}\label{testing-on-all-coefficients}

\begin{itemize}
\tightlist
\item
  Is there a relationship between the response and any of the
  predictors? Namely, is \(H_0: \beta_1=\beta_2=\cdots=\beta_p=0\) true?
\item
  Test statistic: F-statistic \[F=\frac{(TSS-RSS)/p}{RSS/(n-p-1)},\]
  where \(TSS=\sum_{i=1}^n (y_i - \bar{y})^2\) with
  \(\bar{y}=n^{-1}\sum_{i=1}^n y_i\) and
  \(RSS=\sum_{i=1}^n (y_i - \hat{y}_i)^2\)
\item
  If \(H_0\) is true and the linear model assumptions are correct,
  F-statistic should be close to 1 on average; under suitable
  conditions, F-statistic approximately follows an F-distribution
\end{itemize}

\subsection{Testing on all
coefficients}\label{testing-on-all-coefficients-1}

Testing \(H_0: \beta_1=\beta_2=\cdots=\beta_p=0\):

\begin{verbatim}
   value    numdf    dendf 
570.2707   3.0000 196.0000 
       value 
1.575227e-96 
\end{verbatim}

F-statistic: 570.3 with numerator degrees of freedom 3 and denominator
degrees of freedom 196; p-value: \textless{} 2.2e-16

\begin{itemize}
\tightlist
\item
  Conclusion: reject \(H_0\), meaning that \emph{at least one of the
  predictors has a relationship with the response}.
\end{itemize}

\subsection{Testing on some
coefficients}\label{testing-on-some-coefficients}

Is there no relationship between the response and some predictors?
Namely, for some \(1 \le q \le p\), test
\[H_0: \beta_{p-q+1}=\beta_{p-q+2}= \ldots = \beta_{p}=0\]

\begin{itemize}
\tightlist
\item
  Fit
  \(M_0: Y = \beta_0 + \beta_1 X_1 + \ldots + \beta_{p-q} X_{p-q} + \varepsilon\),
  and obtain its residual sum of squares \(RSS_0\)
\item
  Fit
  \(M_1: Y = \beta_0 + \beta_1 X_1 + \ldots + \beta_{p-q} X_{p-q} + \ldots + \beta_p X_p+\varepsilon\),
  and obtain its residual sum of squares \(RSS\)
\item
  Use test statistic \[F = \frac{(RSS_0 - RSS)/q}{RSS/(n-p-1)}\]
\end{itemize}

\subsection{Testing on some
coefficients}\label{testing-on-some-coefficients-1}

When \(H_0\) and model assumptions are true, test statistic
\[F = \frac{(RSS_0 - RSS)/q}{RSS/(n-p-1)}\] approximately follows an
F-distribution with numerator degrees of freedom \(q\) and denominator
degrees of freedom \(n-p-1\)

\subsection{Testing on model fit}\label{testing-on-model-fit}

\begin{itemize}
\tightlist
\item
  \(R^2\) measures the proportion of variance that is explained by the
  postulated model
\item
  With three predictors:
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{>}\StringTok{ }\NormalTok{FitL3c =}\StringTok{ }\KeywordTok{lm}\NormalTok{(sales~TV+radio+newspaper,}\DataTypeTok{data=}\NormalTok{adData)}
\NormalTok{>}\StringTok{ }\KeywordTok{summary}\NormalTok{(FitL3c)$r.squared}
\NormalTok{[}\DecValTok{1}\NormalTok{] }\FloatTok{0.8972106}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  With one predictor:
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{>}\StringTok{ }\NormalTok{FitL3d =}\StringTok{ }\KeywordTok{lm}\NormalTok{(sales~newspaper,}\DataTypeTok{data=}\NormalTok{adData)}
\NormalTok{>}\StringTok{ }\KeywordTok{summary}\NormalTok{(FitL3d)$r.squared}
\NormalTok{[}\DecValTok{1}\NormalTok{] }\FloatTok{0.05212045}
\end{Highlighting}
\end{Shaded}

\section{Interaction terms}\label{interaction-terms}

\subsection{Interaction terms: I}\label{interaction-terms-i}

Consider predicting the average \texttt{sales} (in thousands of dollars)
via budgets in advertisement through \texttt{TV} and \texttt{Radio}.

\begin{itemize}
\item
  Model 1: \(E\)(\texttt{sales}) = \(\beta_0\) + \(\beta_1 \times\)
  \texttt{TV} + \(\beta_2 \times\) \texttt{Radio}
\item
  Model 1: how is the change (in unit) in \(E\)(\texttt{sales}) relates
  to a unit change in \texttt{TV} and/or \texttt{Radio}?
\item
  Is model 1 sensible when changes (in unit) in \(E\)(\texttt{sales})
  are different for a unit change in \texttt{TV} when \texttt{Radio}
  takes different values?
\end{itemize}

\subsection{Interaction terms: I}\label{interaction-terms-i-1}

\begin{itemize}
\tightlist
\item
  If change (in unit) in \(E\)(\texttt{sales}) can be different for a
  unit change in \texttt{TV} at different values of \texttt{Radio} or
  for a unit change in \texttt{Radio} at different values of
  \texttt{TV}, then the model \[
  E(\textsf{sales}) = \beta_0 + \beta_1 \times\textsf{TV} + \beta_2 \times\textsf{Radio}
  \] is no longer suitable\\
\item
  One way to account for this is to introduce an \emph{interaction} term
  and use model \[
  E(\textsf{sales}) = \beta_0 + \beta_1 \times \textsf{TV} + \beta_2 \times\textsf{Radio} + \beta_3 \times\textsf{TV} \times\textsf{Radio}
  \]
\item
  Does the following model do the job? \[
  E(\textsf{sales}) = \beta_0 + \beta_1 \times \textsf{TV} + \beta_2 \times \textsf{Radio} + \beta_3 \times \textsf{TV}^2+ \beta_4 \times \textsf{Radio}^2
  \]
\end{itemize}

\subsection{Interaction terms: I}\label{interaction-terms-i-2}

The model \[
E(\textsf{sales}) = \beta_0 + \beta_1 \times \textsf{TV} + \beta_2 \times\textsf{Radio} + \beta_3 \times\textsf{TV} \times\textsf{Radio}
\] can be written as \[
E(\textsf{sales}) = \beta_0 + \beta_1 \times \textsf{TV} + (\beta_2+  \beta_3 \times\textsf{TV})\times\textsf{Radio}
\] or as \[
E(\textsf{sales}) = \beta_0 + (\beta_1 +\beta_3 \times\textsf{Radio})\times \textsf{TV} + \beta_2 \times\textsf{Radio}
\]

\subsection{Interaction terms: I}\label{interaction-terms-i-3}

Fit the model with interaction:

\begin{verbatim}

Call:
lm(formula = sales ~ TV * radio, data = adData)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.3366 -0.4028  0.1831  0.5948  1.5246 

Coefficients:
             Estimate Std. Error t value Pr(>|t|)    
(Intercept) 6.750e+00  2.479e-01  27.233   <2e-16 ***
TV          1.910e-02  1.504e-03  12.699   <2e-16 ***
radio       2.886e-02  8.905e-03   3.241   0.0014 ** 
TV:radio    1.086e-03  5.242e-05  20.727   <2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9435 on 196 degrees of freedom
Multiple R-squared:  0.9678,    Adjusted R-squared:  0.9673 
F-statistic:  1963 on 3 and 196 DF,  p-value: < 2.2e-16
\end{verbatim}

\subsection{Interaction terms: II}\label{interaction-terms-ii}

Consider predicting the average \texttt{Balance} (of a credit card)
using information on if a user is a \texttt{Student} (``Yes'' or ``No'')
and his/her \texttt{Income}

\begin{itemize}
\tightlist
\item
  Model 0: \(E\)(\texttt{Balance}) = \(\beta_0\) + \(\beta_1 \times\)
  \texttt{Income}
\item
  Model 1: \(E\)(\texttt{Balance}) = \(\beta_0\) + \(\beta_1 \times\)
  \texttt{Student} + \(\beta_2 \times\) \texttt{Income}
\item
  Model 2: \(E\)(\texttt{Balance}) = \(\beta_0\) + \(\beta_1 \times\)
  \texttt{Student} + \(\beta_2 \times\) \texttt{Income} +
  \(\beta_3 \times\) \texttt{Student} \(\times\) \texttt{Income}
\end{itemize}

Coding in R: \texttt{Student}=``No'' is coded as 0 and the baseline, and
\texttt{Student}=``Yes'' as 1

\subsection{Interaction terms: II}\label{interaction-terms-ii-1}

\begin{center}\includegraphics[width=0.95\linewidth]{Stat435LectureNotes3_notes_files/figure-latex/unnamed-chunk-11-1} \end{center}

\subsection{Interaction terms: II}\label{interaction-terms-ii-2}

Fit the model with interaction:

\begin{verbatim}

Call:
lm(formula = Balance ~ Student * Income, data = creditData)

Residuals:
    Min      1Q  Median      3Q     Max 
-773.39 -325.70  -41.13  321.65  814.04 

Coefficients:
                  Estimate Std. Error t value Pr(>|t|)    
(Intercept)       200.6232    33.6984   5.953 5.79e-09 ***
StudentYes        476.6758   104.3512   4.568 6.59e-06 ***
Income              6.2182     0.5921  10.502  < 2e-16 ***
StudentYes:Income  -1.9992     1.7313  -1.155    0.249    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 391.6 on 396 degrees of freedom
Multiple R-squared:  0.2799,    Adjusted R-squared:  0.2744 
F-statistic:  51.3 on 3 and 396 DF,  p-value: < 2.2e-16
\end{verbatim}

\section{Diagnostics}\label{diagnostics-1}

\subsection{Diagnostics}\label{diagnostics-2}

\begin{itemize}
\tightlist
\item
  Diagnostics for multiple linear regression are very similar to those
  for simple linear regression with a quantitative predictor.
\item
  Additional task: check on collinearity and \emph{variance inflation
  factor (VIF)}
\end{itemize}

\subsection{Collinearity}\label{collinearity}

Collinearity

\begin{itemize}
\tightlist
\item
  refers to the situation in which two or more predictor variables are
  closely related to each other
\item
  \emph{often inflates the variances of estimated coefficients and makes
  the model unstable}
\item
  can be measured by the \emph{variance inflation factor (VIF)}
\end{itemize}

\emph{A VIF value that exceeds 5 or 10 indicates a problematic amount of
collinearity}

\emph{Note:} VIF(\(\hat{\beta}_j) = \frac{1}{1-R^2_{X_j|X_{-j}}}\);
collinearity implies \(R^2_{X_j|X_{-j}} \approx 1\)

\subsection{Collinearity}\label{collinearity-1}

Collinearity among \texttt{Limit} and \texttt{Rating}:

\begin{center}\includegraphics[width=0.7\linewidth]{Stat435LectureNotes3_notes_files/figure-latex/L3D1-1} \end{center}

\subsection{Collinearity}\label{collinearity-2}

Model \texttt{Balance\textasciitilde{}Age+Limit}:

\begin{verbatim}
# A tibble: 3 x 5
  term        estimate std.error statistic   p.value
  <chr>          <dbl>     <dbl>     <dbl>     <dbl>
1 (Intercept) -173.     43.8         -3.96 9.01e-  5
2 Age           -2.29    0.672       -3.41 7.23e-  4
3 Limit          0.173   0.00503     34.5  1.63e-121
\end{verbatim}

Model \texttt{Balance\textasciitilde{}Rating+Limit}:

\begin{verbatim}
# A tibble: 3 x 5
  term         estimate std.error statistic  p.value
  <chr>           <dbl>     <dbl>     <dbl>    <dbl>
1 (Intercept) -378.       45.3       -8.34  1.21e-15
2 Rating         2.20      0.952      2.31  2.13e- 2
3 Limit          0.0245    0.0638     0.384 7.01e- 1
\end{verbatim}

\emph{Note:} compare standard errors of \(\hat{\beta}_{\textsf{Limit}}\)
in both models

\subsection{Collinearity}\label{collinearity-3}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{>}\StringTok{ }\NormalTok{FitL3f =}\StringTok{ }\KeywordTok{lm}\NormalTok{(Balance~Age+Rating+Limit,}\DataTypeTok{data=}\NormalTok{creditData)}
\NormalTok{>}\StringTok{ }\KeywordTok{library}\NormalTok{(car)}
\NormalTok{>}\StringTok{ }\KeywordTok{vif}\NormalTok{(FitL3f)}
       \NormalTok{Age     Rating      Limit }
  \FloatTok{1.011385} \FloatTok{160.668301} \FloatTok{160.592880} 
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  VIFs indicate considerable collinearity in the data
\end{itemize}

In case of collinearity, either drop one of the problematic variables or
combine some closely related variables

\section{Non-linear models}\label{non-linear-models}

\subsection{Non-linear relationship}\label{non-linear-relationship}

If there is evidence on a non-linear relationship between response and
predictors, we can

\begin{itemize}
\tightlist
\item
  add high-order terms into the model (or employ more advanced
  non-linear methods); e.g., \[E(Y)=\beta_0+\beta_1 X + \beta_2 X^2\]
\item
  transform predictors (and/or response); e.g., e.g.,
  \(E(Y)=\beta_0+\beta_1 \times f(X)\), where \(f\) can be \(\log(X)\)
  or \(\sqrt{X}\)
\end{itemize}

\subsection{License and session
Information}\label{license-and-session-information}

\href{http://math.wsu.edu/faculty/xchen/stat412/LICENSE.html}{License}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{>}\StringTok{ }\KeywordTok{sessionInfo}\NormalTok{()}
\NormalTok{R version }\FloatTok{3.5.0} \NormalTok{(}\DecValTok{2018-04-23}\NormalTok{)}
\NormalTok{Platform:}\StringTok{ }\NormalTok{x86_64-w64-mingw32/}\KeywordTok{x64} \NormalTok{(}\DecValTok{64}\NormalTok{-bit)}
\NormalTok{Running under:}\StringTok{ }\NormalTok{Windows }\DecValTok{10} \KeywordTok{x64} \NormalTok{(build }\DecValTok{19045}\NormalTok{)}

\NormalTok{Matrix products:}\StringTok{ }\NormalTok{default}

\NormalTok{locale:}
\NormalTok{[}\DecValTok{1}\NormalTok{] LC_COLLATE=English_United States}\FloatTok{.1252} 
\NormalTok{[}\DecValTok{2}\NormalTok{] LC_CTYPE=English_United States}\FloatTok{.1252}   
\NormalTok{[}\DecValTok{3}\NormalTok{] LC_MONETARY=English_United States}\FloatTok{.1252}
\NormalTok{[}\DecValTok{4}\NormalTok{] LC_NUMERIC=C                          }
\NormalTok{[}\DecValTok{5}\NormalTok{] LC_TIME=English_United States}\FloatTok{.1252}    

\NormalTok{attached base packages:}
\NormalTok{[}\DecValTok{1}\NormalTok{] stats     graphics  grDevices utils     datasets  methods  }
\NormalTok{[}\DecValTok{7}\NormalTok{] base     }

\NormalTok{other attached packages:}
\NormalTok{[}\DecValTok{1}\NormalTok{] car_3}\FloatTok{.0}\DecValTok{-2}     \NormalTok{carData_3}\FloatTok{.0}\DecValTok{-2} \NormalTok{broom_0}\FloatTok{.5.1}   \NormalTok{gridExtra_2}\FloatTok{.3}
\NormalTok{[}\DecValTok{5}\NormalTok{] ggplot2_3}\FloatTok{.1.0} \NormalTok{knitr_1}\FloatTok{.21}   

\NormalTok{loaded via a }\KeywordTok{namespace} \NormalTok{(and not attached):}
\StringTok{ }\NormalTok{[}\DecValTok{1}\NormalTok{] tidyselect_0}\FloatTok{.2.5}  \NormalTok{xfun_0}\FloatTok{.4}          \NormalTok{purrr_0}\FloatTok{.2.5}      
 \NormalTok{[}\DecValTok{4}\NormalTok{] haven_2}\FloatTok{.0.0}       \NormalTok{lattice_0}\FloatTok{.20}\DecValTok{-35}   \NormalTok{colorspace_1}\FloatTok{.3}\DecValTok{-2} 
 \NormalTok{[}\DecValTok{7}\NormalTok{] generics_0}\FloatTok{.0.2}    \NormalTok{htmltools_0}\FloatTok{.3.6}   \NormalTok{yaml_2}\FloatTok{.2.0}       
\NormalTok{[}\DecValTok{10}\NormalTok{] utf8_1}\FloatTok{.1.4}        \NormalTok{rlang_0}\FloatTok{.4.4}       \NormalTok{pillar_1}\FloatTok{.3.1}     
\NormalTok{[}\DecValTok{13}\NormalTok{] foreign_0}\FloatTok{.8}\DecValTok{-70}    \NormalTok{glue_1}\FloatTok{.3.0}        \NormalTok{withr_2}\FloatTok{.1.2}      
\NormalTok{[}\DecValTok{16}\NormalTok{] readxl_1}\FloatTok{.2.0}      \NormalTok{plyr_1}\FloatTok{.8.4}        \NormalTok{stringr_1}\FloatTok{.3.1}    
\NormalTok{[}\DecValTok{19}\NormalTok{] cellranger_1}\FloatTok{.1.0}  \NormalTok{munsell_0}\FloatTok{.5.0}     \NormalTok{gtable_0}\FloatTok{.2.0}     
\NormalTok{[}\DecValTok{22}\NormalTok{] zip_1}\FloatTok{.0.0}         \NormalTok{evaluate_0}\FloatTok{.13}     \NormalTok{labeling_0}\FloatTok{.3}     
\NormalTok{[}\DecValTok{25}\NormalTok{] rio_0}\FloatTok{.5.16}        \NormalTok{forcats_0}\FloatTok{.3.0}     \NormalTok{curl_3}\FloatTok{.2}         
\NormalTok{[}\DecValTok{28}\NormalTok{] fansi_0}\FloatTok{.4.0}       \NormalTok{Rcpp_1}\FloatTok{.0.12}       \NormalTok{scales_1}\FloatTok{.0.0}     
\NormalTok{[}\DecValTok{31}\NormalTok{] backports_1}\FloatTok{.1.3}   \NormalTok{abind_1}\FloatTok{.4}\DecValTok{-5}       \NormalTok{hms_0}\FloatTok{.4.2}        
\NormalTok{[}\DecValTok{34}\NormalTok{] digest_0}\FloatTok{.6.18}     \NormalTok{openxlsx_4}\FloatTok{.1.0}    \NormalTok{stringi_1}\FloatTok{.2.4}    
\NormalTok{[}\DecValTok{37}\NormalTok{] dplyr_0}\FloatTok{.8.4}       \NormalTok{grid_3}\FloatTok{.5.0}        \NormalTok{cli_1}\FloatTok{.0.1}        
\NormalTok{[}\DecValTok{40}\NormalTok{] tools_3}\FloatTok{.5.0}       \NormalTok{magrittr_1}\FloatTok{.5}      \NormalTok{lazyeval_0}\FloatTok{.2.1}   
\NormalTok{[}\DecValTok{43}\NormalTok{] tibble_2}\FloatTok{.1.3}      \NormalTok{crayon_1}\FloatTok{.3.4}      \NormalTok{tidyr_0}\FloatTok{.8.2}      
\NormalTok{[}\DecValTok{46}\NormalTok{] pkgconfig_2}\FloatTok{.0.2}   \NormalTok{data.table_1}\FloatTok{.11.8} \NormalTok{assertthat_0}\FloatTok{.2.0} 
\NormalTok{[}\DecValTok{49}\NormalTok{] rmarkdown_1}\FloatTok{.11}    \NormalTok{rstudioapi_0}\FloatTok{.8}    \NormalTok{R6_2}\FloatTok{.3.0}         
\NormalTok{[}\DecValTok{52}\NormalTok{] nlme_3}\FloatTok{.1}\DecValTok{-137}      \NormalTok{compiler_3}\FloatTok{.5.0}   
\end{Highlighting}
\end{Shaded}


\end{document}
